### PR TITLE
Restart server and auto refresh browser on changes!

### PR DESCRIPTION
**Pull request by samarpanda**
## Restart server and auto refresh browser on changes!

No manual refresh of browser on changing html files. No need to restart server on changing `index.js`.
Added few dev dependencies for this feature `gulp`, `browser-sync` and `gulp-nodemon`.
## npm start

``` shell
[samar@sp falcor-express-demo [±] watch_reload 8b4db6f ✗]$ npm start

> falcor-express-demo@0.0.1 start /Users/samar/Projects/falcor-express-demo
> gulp

[11:43:17] Using gulpfile ~/Projects/falcor-express-demo/gulpfile.js
[11:43:17] Starting 'nodemon'...
[11:43:17] [nodemon] v1.4.1
[11:43:17] [nodemon] to restart at any time, enter `rs`
[11:43:17] [nodemon] watching: *.*
[11:43:17] [nodemon] starting `node index.js`
[11:43:17] Finished 'nodemon' after 193 ms
[11:43:17] Starting 'browser-sync'...
[11:43:20] Finished 'browser-sync' after 2.3 s
[11:43:20] Starting 'default'...
[11:43:20] Finished 'default' after 14 μs
[BS] Proxying: http://localhost:9091
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:9090
    External: http://192.168.31.130:9090
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.31.130:3001
 ---------------------------------------
[BS] Watching files...
[BS] File changed: index.html
[BS] File changed: index.html
[11:44:41] [nodemon] restarting due to changes...
[11:44:42] [nodemon] starting `node index.js`
```

### CODE REVIEW

**Comment by tbranyen** [comment]
Could this be re-implemented without Gulp? Might be easier to reconcile merging with something less opinionated in this ultra-basic project demo.

**Comment by samarpanda** [comment]
@tbranyen Sure, will add a PR without Gulp.

**Comment by jameswomack** [comment]
:+1: (at least it wasn't Grunt though)

**Comment by samarpanda** [comment]
Re-implemented without gulp / grunt for this project. https://github.com/Netflix/falcor-express-demo/pull/7

**Comment by samarpanda** [comment]
Closing this PR as of now. Feel free to reopen if you need. Thanks.

**Pull request closed without merging**
